### ISSUE TITLE
Chapter 4 code has not been upgraded to OpenCV 4

### ISSUE THREAD

**Issue by Genyz** [PacktPublishing/Mastering-OpenCV-4-Third-Edition#2]
Hi,

Many C++ files in Chapter 4 still have OpenCV C-style, and are no more compatible with OpenCV 4. 

Issues concern such features as :
- include files
For example : <cv.h> ...
- processing flags : 
For example : CV_BGR2GRAY --> cv::COLOR_BGR2GRAY or CV_THRESH_BINARY_INV --> cv::ThresholdTypes::THRESH_BINARY_INV
- etc ...

I haven't worked with the other chapters of the book yet, but it seems that there is old-style code in Chapter 7 too.

Furthermore, I had to modify CMakeList.txt file to be able to generate the .sln project under Windows 10 (issue with conanbuild).
Seems that at least Chapter 4 content has not been upgraded on github.

Best regards,

**Comment by royshil** [comment]
I fixed the build issues and OpenCV 4 APIs, also retouched the READMEs and formatted the entire code base.
